-- MySQL Script generated by MySQL Workbench
-- 06/15/15 11:10:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cars
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cars` DEFAULT CHARACTER SET utf8 ;
USE `cars` ;

-- -----------------------------------------------------
-- Table `cars`.`joining_process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cars`.`joining_process` (
  `id_joining_process` INT(11) NOT NULL AUTO_INCREMENT,
  `spot_welds` FLOAT NULL DEFAULT NULL,
  `arc_welding` FLOAT NULL DEFAULT NULL,
  `friction_stir_welding` FLOAT NULL DEFAULT NULL,
  `laser_welding` FLOAT NULL DEFAULT NULL,
  `conventional_brazing` FLOAT NULL DEFAULT NULL,
  `adhesive_joining` FLOAT NULL DEFAULT NULL,
  `rivets` FLOAT NULL DEFAULT NULL,
  `clinch_spots` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_joining_process`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cars`.`lengths`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cars`.`lengths` (
  `id_lengths` INT(11) NOT NULL AUTO_INCREMENT,
  `length` INT(11) NULL DEFAULT NULL,
  `width` INT(11) NULL DEFAULT NULL,
  `height` INT(11) NULL DEFAULT NULL,
  `track_front` INT(11) NULL DEFAULT NULL,
  `track_rear` INT(11) NULL DEFAULT NULL,
  `wheelbase` INT(11) NULL DEFAULT NULL,
  `contact_area` FLOAT NULL DEFAULT NULL,
  `lengthscol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_lengths`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cars`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cars`.`manufacturer` (
  `id_manufacturer` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_manufacturer`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cars`.`material_mix`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cars`.`material_mix` (
  `id_material_mix` INT(11) NOT NULL AUTO_INCREMENT,
  `low_strength_steel` FLOAT NULL DEFAULT NULL,
  `hss` FLOAT NULL DEFAULT NULL,
  `ahss` FLOAT NULL DEFAULT NULL,
  `stainless_steel` FLOAT NULL DEFAULT NULL,
  `uhss` FLOAT NULL DEFAULT NULL,
  `aluminium` FLOAT NULL DEFAULT NULL,
  `magnesium` FLOAT NULL DEFAULT NULL,
  `frp` FLOAT NULL DEFAULT NULL,
  `smc` FLOAT NULL DEFAULT NULL,
  `thermoplastics` FLOAT NULL DEFAULT NULL,
  `elastomers` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_material_mix`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cars`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cars`.`model` (
  `id_model` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `model_year` INT(11) NULL DEFAULT NULL,
  `segment` VARCHAR(45) NULL DEFAULT NULL,
  `internaloem` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_model`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cars`.`production`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cars`.`production` (
  `id_production` INT(11) NOT NULL AUTO_INCREMENT,
  `process` FLOAT NULL DEFAULT NULL,
  `re_use_factor` FLOAT NULL DEFAULT NULL,
  `mechanisation` FLOAT NULL DEFAULT NULL,
  `intended_production_vol` INT(11) NULL DEFAULT NULL,
  `production_lead_time` TIME NULL DEFAULT NULL,
  `cycle_time` TIME NULL DEFAULT NULL,
  `degree_material_utilisation` FLOAT NULL DEFAULT NULL,
  `no_parts` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_production`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cars`.`production_sites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cars`.`production_sites` (
  `id_production_sites` INT(11) NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_production_sites`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cars`.`stiffness_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cars`.`stiffness_data` (
  `id_stiffness_data` INT(11) NOT NULL AUTO_INCREMENT,
  `first_trimmed_body` FLOAT NULL DEFAULT NULL,
  `second_trimmed_body` FLOAT NULL DEFAULT NULL,
  `first_body` FLOAT NULL DEFAULT NULL,
  `second_body` FLOAT NULL DEFAULT NULL,
  `torsional` FLOAT NULL DEFAULT NULL,
  `bend` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_stiffness_data`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cars`.`weights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cars`.`weights` (
  `id_weights` INT(11) NOT NULL AUTO_INCREMENT,
  `biw` FLOAT NULL DEFAULT NULL,
  `front_doors` FLOAT NULL DEFAULT NULL,
  `rear_doors` FLOAT NULL DEFAULT NULL,
  `hood` FLOAT NULL DEFAULT NULL,
  `tailgate` FLOAT NULL DEFAULT NULL,
  `front_fenders` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_weights`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
